language: php

php:
  - 7.0

services:
  - docker

before_install:
  - docker build -f ./docker/lemp-l5code/Dockerfile --tag lemp:travis ./docker/lemp-l5code
  - sleep 15
  - docker run -d --name myapp -v `pwd`:/var/www/myapp -v `pwd`/docker/mysql_datadir:/var/lib/mysql -p 8000:80 -p 33060:3306 lemp:travis

install:
  - composer self-update
  - travis_retry composer install --no-interaction --no-scripts --prefer-source --dev

before_script:
  - TRAVIS=true
  - cp .env.example .env
  - php artisan key:generate
  - touch tests/database.sqlite
  - php artisan migrate --seed --database=testing

script:
  - vendor/bin/phpunit
  - docker container ls
  - curl -s -XGET http://localhost:8000/health
  - docker exec -it myapp mysql -v -e "SELECT 1;"

matrix:
  fast_finish: true
